DROP TABLE Productos;

DROP TABLE ItemCompras;



CREATE TABLE Productos(
Id_P NUMBER NOT NULL,
Nombre VARCHAR2(50) NOT NULL,
Codigo VARCHAR2(50) NOT NULL,
DireccionImagen VARCHAR2(50) NOT NULL,
Id_I NUMBER NOT NULL,
Id_A NUMBER NOT NULL,
Id_PRO NUMBER NOT NULL,
PRIMARY KEY(Id_P),
FOREIGN KEY(Id_I) REFERENCES ItemCompras(Id_I) ON DELETE CASCADE,
FOREIGN KEY(Id_A) REFERENCES Almacenes(Id_A) ON DELETE CASCADE,
FOREIGN KEY(Id_PRO) REFERENCES Proveedores(Id_PRO) ON DELETE CASCADE);



CREATE TABLE ItemCompras(
Id_I NUMBER NOT NULL,
Stock NUMBER(9,2) NOT NULL,
Precio NUMBER(9,2) NOT NULL,
PRIMARY KEY(Id_I));
